import type { EnvField } from "../introspect.js";

export type ComposeStyle = "service" | "env-file";

export interface ComposeFragmentOptions {
  /**
   * Output style:
   *   - `"service"` (default) — a `services:` fragment with one entry
   *     under `environment:`, ready to merge into a `compose.yml`.
   *     Values use `${VAR}` interpolation so Compose resolves them
   *     from the host shell / `.env`.
   *   - `"env-file"` — a plain `.env`-style file you can reference as
   *     `env_file:` in compose. Defaults match the schema; secrets get
   *     a REPLACE_ME placeholder unless overridden via `values`.
   */
  style?: ComposeStyle;
  /**
   * Service name used in the `services:` fragment. Default: `"app"`.
   * Ignored when `style === "env-file"`.
   */
  serviceName?: string;
  /**
   * Pre-fill specific variables with concrete values (overrides
   * `${VAR}` interpolation for `service` style, or REPLACE_ME for
   * `env-file` style).
   */
  values?: Record<string, string | number | boolean>;
  /** Header banner placed at the top of the output. */
  header?: string;
  /** End-of-line. Default: `"\n"`. */
  eol?: string;
}

/**
 * Generate a Docker Compose fragment from introspected env fields.
 *
 * `style: "service"` (default) — a complete `services:` snippet that
 * you can paste / `cat >> compose.yml`:
 *
 * ```yaml
 * services:
 *   app:
 *     environment:
 *       APP_ENV: "${APP_ENV:-local}"
 *       DB_HOST: "${DB_HOST}"
 *       DB_PASSWORD: "${DB_PASSWORD}"
 * ```
 *
 * `style: "env-file"` — a flat `.env`-style file with placeholders,
 * intended for `env_file:` references in your compose file.
 *
 * Secret values are never inlined unless explicitly overridden via
 * `options.values` — they always resolve through Compose's
 * `${VAR}` mechanism so they stay in the host environment.
 */
export function generateComposeFragment(
  fields: readonly EnvField[],
  options: ComposeFragmentOptions = {},
): string {
  const style: ComposeStyle = options.style ?? "service";
  const eol = options.eol ?? "\n";
  const values = options.values ?? {};

  if (style === "env-file") {
    return renderEnvFile(fields, values, options.header, eol);
  }

  const serviceName = options.serviceName ?? "app";
  const header =
    options.header ??
    [
      "# Generated by @env-kit/node-settings.",
      "# Re-run `node-settings generate compose --name <service>` to refresh.",
      "# Values use ${VAR} interpolation — set them in your shell or .env.",
    ].join(eol);

  const lines: string[] = [header, ""];
  lines.push("services:");
  lines.push(`  ${serviceName}:`);
  lines.push(`    environment:`);
  for (const field of fields) {
    if (field.description) {
      for (const descLine of field.description.split(/\r?\n/)) {
        lines.push(`      # ${descLine}`);
      }
    }
    const override = values[field.key];
    if (override !== undefined) {
      lines.push(`      ${field.key}: ${quoteYaml(String(override))}`);
    } else if (field.defaultValue !== undefined && !field.secret) {
      // `${VAR:-default}` lets Compose fall back to schema default.
      lines.push(
        `      ${field.key}: ${quoteYaml(`\${${field.key}:-${String(field.defaultValue)}}`)}`,
      );
    } else {
      lines.push(
        `      ${field.key}: ${quoteYaml(`\${${field.key}}`)}`,
      );
    }
  }

  while (lines.at(-1) === "") lines.pop();
  lines.push("");
  return lines.join(eol);
}

function renderEnvFile(
  fields: readonly EnvField[],
  values: Record<string, string | number | boolean>,
  customHeader: string | undefined,
  eol: string,
): string {
  const header =
    customHeader ??
    [
      "# Generated by @env-kit/node-settings (compose env-file style).",
      "# Reference this in compose.yml as: env_file: ./.env.compose",
    ].join(eol);
  const lines: string[] = [header, ""];
  for (const field of fields) {
    if (field.description) {
      for (const descLine of field.description.split(/\r?\n/)) {
        lines.push(`# ${descLine}`);
      }
    }
    const override = values[field.key];
    let rendered: string;
    if (override !== undefined) {
      rendered = String(override);
    } else if (field.secret || field.required) {
      rendered = "REPLACE_ME";
    } else if (field.defaultValue !== undefined) {
      rendered = String(field.defaultValue);
    } else {
      rendered = "";
    }
    lines.push(`${field.key}=${rendered}`);
  }
  while (lines.at(-1) === "") lines.pop();
  lines.push("");
  return lines.join(eol);
}

function quoteYaml(value: string): string {
  // Always double-quote, escape backslashes and double quotes. This keeps
  // ${VAR} literal in the YAML so Compose can interpolate at parse time.
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}
