import { describe, expect, it } from "vitest";
import { z } from "zod";
import { introspectEnvSchema } from "../introspect.js";
import { generateEnvExample } from "./env-example.js";

const schema = z.object({
  APP_ENV: z.enum(["local", "dev", "prod"]).default("local"),
  DB_HOST: z.string().describe("primary db host"),
  DB_PASSWORD: z.string(),
  PORT: z.coerce.number().default(3000),
});

describe("generateEnvExample", () => {
  const fields = introspectEnvSchema(schema);

  it("renders a banner followed by every key", () => {
    const out = generateEnvExample(fields);
    expect(out).toContain("# Generated by @env-kit/node-settings.");
    expect(out).toContain("APP_ENV=local");
    expect(out).toContain("DB_HOST=");
    expect(out).toContain("PORT=3000");
  });

  it("groups secrets into their own section", () => {
    const out = generateEnvExample(fields);
    const secretIdx = out.indexOf("# --- Secrets ---");
    const passwordIdx = out.indexOf("DB_PASSWORD=");
    const hostIdx = out.indexOf("DB_HOST=");
    expect(secretIdx).toBeGreaterThan(-1);
    expect(passwordIdx).toBeGreaterThan(secretIdx);
    expect(hostIdx).toBeLessThan(secretIdx);
  });

  it("annotates required / optional and emits the description", () => {
    const out = generateEnvExample(fields);
    expect(out).toMatch(/# DB_HOST \(string, required\)/);
    expect(out).toContain("# primary db host");
    expect(out).toMatch(/# APP_ENV \(enum, optional, enum: local\|dev\|prod, default: "local"\)/);
  });

  it("masks secret defaults by default", () => {
    const schemaWithSecretDefault = z.object({
      API_TOKEN: z.string().default("dev-token-do-not-ship"),
    });
    const fields = introspectEnvSchema(schemaWithSecretDefault);
    const masked = generateEnvExample(fields);
    expect(masked).toContain("API_TOKEN=");
    expect(masked).not.toContain("dev-token-do-not-ship");

    const unmasked = generateEnvExample(fields, { maskSecretDefaults: false });
    expect(unmasked).toContain("API_TOKEN=dev-token-do-not-ship");
  });
});
