import type { EnvField } from "../introspect.js";
import type { SettingsLoader } from "../define-settings.js";
import type { z } from "zod";

export interface EnvExampleOptions {
  /** Header banner placed at the top of the file. */
  header?: string;
  /** Group secret variables under a separate `# Secrets` section. Default: true. */
  groupSecrets?: boolean;
  /** Mask secret default values rather than emitting them. Default: true. */
  maskSecretDefaults?: boolean;
  /**
   * Pre-fill specific env vars with concrete values. Useful for
   * generating per-environment samples where `APP_ENV` is set to a
   * known branch name. Secret keys still respect `maskSecretDefaults`
   * unless explicitly listed here.
   */
  values?: Record<string, string | number | boolean>;
  /** End-of-line. Default: `"\n"`. */
  eol?: string;
}

/**
 * Generate the contents of a `.env.example` file from introspected env
 * field metadata.
 *
 * Each entry includes a comment summarising the type, requiredness,
 * allowed values (for enums), and the field description. The line itself
 * is left blank for required fields or pre-filled with the schema default
 * (or with `options.values[key]` if supplied).
 */
export function generateEnvExample(
  fields: readonly EnvField[],
  options: EnvExampleOptions = {},
): string {
  const eol = options.eol ?? "\n";
  const groupSecrets = options.groupSecrets ?? true;
  const maskSecretDefaults = options.maskSecretDefaults ?? true;
  const values = options.values ?? {};

  const lines: string[] = [];
  const header =
    options.header ??
    [
      "# Generated by @env-kit/node-settings.",
      "# Re-run `node-settings generate env-example` to refresh.",
      "# Required values are left blank — fill them in before booting the app.",
    ].join(eol);
  lines.push(header, "");

  const ordered = groupSecrets
    ? [
        ...fields.filter((f) => !f.secret),
        ...(fields.some((f) => f.secret)
          ? ["", "# --- Secrets ---", ""]
          : []),
        ...fields.filter((f) => f.secret),
      ]
    : [...fields];

  for (const entry of ordered) {
    if (typeof entry === "string") {
      lines.push(entry);
      continue;
    }
    lines.push(...renderField(entry, maskSecretDefaults, values));
    lines.push("");
  }

  while (lines.length > 0 && lines[lines.length - 1] === "") lines.pop();
  return lines.join(eol) + eol;
}

function renderField(
  field: EnvField,
  maskSecretDefaults: boolean,
  values: Record<string, string | number | boolean>,
): string[] {
  const hideDefault = field.secret && maskSecretDefaults;
  const meta: string[] = [];
  meta.push(field.type);
  meta.push(field.required ? "required" : "optional");
  if (field.enumValues) meta.push(`enum: ${field.enumValues.join("|")}`);
  if (field.defaultValue !== undefined && !hideDefault) {
    meta.push(`default: ${formatDefault(field.defaultValue)}`);
  }
  if (field.secret) meta.push("secret");

  const out: string[] = [];
  out.push(`# ${field.key} (${meta.join(", ")})`);
  if (field.description) {
    for (const descLine of field.description.split(/\r?\n/)) {
      out.push(`# ${descLine}`);
    }
  }

  const explicitValue = values[field.key];
  let value = "";
  if (explicitValue !== undefined) {
    value = formatValue(explicitValue);
  } else if (field.defaultValue !== undefined) {
    if (field.secret && maskSecretDefaults) {
      value = "";
    } else {
      value = formatValue(field.defaultValue);
    }
  }
  out.push(`${field.key}=${value}`);
  return out;
}

function formatDefault(value: unknown): string {
  if (typeof value === "string") return JSON.stringify(value);
  return String(value);
}

function formatValue(value: unknown): string {
  if (typeof value === "string") {
    return /[\s"'#]/.test(value) ? JSON.stringify(value) : value;
  }
  return String(value);
}

export interface PerEnvExamplesOptions
  extends Omit<EnvExampleOptions, "values" | "header"> {
  /**
   * Restrict to a subset of `perEnv` branches. Defaults to every branch.
   */
  envs?: readonly string[];
  /**
   * If true (default), prepend a comment block summarising the layered
   * config the branch will resolve to at runtime.
   */
  includeConfigSummary?: boolean;
}

/**
 * Generate one `.env` example per `perEnv` branch, with the loader's
 * `envKey` (e.g. `APP_ENV`) pre-filled with the branch name. Pairs
 * cleanly with the `node-settings generate envs` CLI subcommand.
 *
 * @example
 * ```ts
 * const examples = generatePerEnvExamples(settings);
 * // {
 * //   local: "# .env example for APP_ENV=local ...",
 * //   dev:   "# .env example for APP_ENV=dev   ...",
 * //   prod:  "# .env example for APP_ENV=prod  ...",
 * // }
 * ```
 */
export function generatePerEnvExamples<
  TSchema extends z.ZodObject<z.ZodRawShape>,
  TConfig extends object,
  TSettings extends object,
>(
  loader: SettingsLoader<TSchema, TConfig, TSettings>,
  options: PerEnvExamplesOptions = {},
): Record<string, string> {
  const includeSummary = options.includeConfigSummary ?? true;
  const envs = options.envs ?? Object.keys(loader.resolved.perEnv);
  const result: Record<string, string> = {};

  for (const env of envs) {
    const branch = loader.resolved.perEnv[env];
    if (!branch) continue;

    const summary = includeSummary
      ? buildConfigSummary(loader.resolved.defaults, branch)
      : undefined;
    const header = [
      `# .env example for ${loader.resolved.envKey}=${env}`,
      `# Generated by @env-kit/node-settings.`,
      "# Required values are left blank — fill them in before booting the app.",
      ...(summary ? ["#", ...summary] : []),
    ].join(options.eol ?? "\n");

    result[env] = generateEnvExample(loader.envFields, {
      ...options,
      header,
      values: { [loader.resolved.envKey]: env },
    });
  }

  return result;
}

function buildConfigSummary(
  defaults: Record<string, unknown>,
  branch: Record<string, unknown>,
): string[] {
  const merged = deepMergeForSummary(defaults, branch);
  if (Object.keys(merged).length === 0) return [];
  const flat = flattenObject(merged);
  return [
    "# When this env loads, the layered config resolves to:",
    ...Object.entries(flat).map(([k, v]) => `#   ${k}: ${formatSummaryValue(v)}`),
  ];
}

function deepMergeForSummary(
  defaults: Record<string, unknown>,
  branch: Record<string, unknown>,
): Record<string, unknown> {
  const out: Record<string, unknown> = { ...defaults };
  for (const [key, value] of Object.entries(branch)) {
    const existing = out[key];
    if (
      isPlainObject(value) &&
      isPlainObject(existing)
    ) {
      out[key] = deepMergeForSummary(
        existing as Record<string, unknown>,
        value as Record<string, unknown>,
      );
    } else {
      out[key] = value;
    }
  }
  return out;
}

function flattenObject(
  obj: Record<string, unknown>,
  prefix = "",
): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(obj)) {
    const path = prefix ? `${prefix}.${key}` : key;
    if (isPlainObject(value)) {
      Object.assign(out, flattenObject(value as Record<string, unknown>, path));
    } else {
      out[path] = value;
    }
  }
  return out;
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  if (value === null || typeof value !== "object") return false;
  const proto = Object.getPrototypeOf(value);
  return proto === Object.prototype || proto === null;
}

function formatSummaryValue(value: unknown): string {
  if (typeof value === "string") return JSON.stringify(value);
  if (Array.isArray(value)) return JSON.stringify(value);
  return String(value);
}
