import type { EnvField } from "../introspect.js";

export interface EnvExampleOptions {
  /** Header banner placed at the top of the file. */
  header?: string;
  /** Group secret variables under a separate `# Secrets` section. Default: true. */
  groupSecrets?: boolean;
  /** Mask secret default values rather than emitting them. Default: true. */
  maskSecretDefaults?: boolean;
  /** End-of-line. Default: `"\n"`. */
  eol?: string;
}

/**
 * Generate the contents of a `.env.example` file from introspected env
 * field metadata.
 *
 * Each entry includes a comment summarising the type, requiredness,
 * allowed values (for enums), and the field description. The line itself
 * is left blank for required fields or pre-filled with the schema default.
 */
export function generateEnvExample(
  fields: readonly EnvField[],
  options: EnvExampleOptions = {},
): string {
  const eol = options.eol ?? "\n";
  const groupSecrets = options.groupSecrets ?? true;
  const maskSecretDefaults = options.maskSecretDefaults ?? true;

  const lines: string[] = [];
  const header =
    options.header ??
    [
      "# Generated by @changsik00/node-settings.",
      "# Re-run `node-settings generate env-example` to refresh.",
      "# Required values are left blank — fill them in before booting the app.",
    ].join(eol);
  lines.push(header, "");

  const ordered = groupSecrets
    ? [
        ...fields.filter((f) => !f.secret),
        ...(fields.some((f) => f.secret)
          ? ["", "# --- Secrets ---", ""]
          : []),
        ...fields.filter((f) => f.secret),
      ]
    : [...fields];

  for (const entry of ordered) {
    if (typeof entry === "string") {
      lines.push(entry);
      continue;
    }
    lines.push(...renderField(entry, maskSecretDefaults));
    lines.push("");
  }

  // Trim trailing blank line, then re-add one final newline.
  while (lines.length > 0 && lines[lines.length - 1] === "") lines.pop();
  return lines.join(eol) + eol;
}

function renderField(field: EnvField, maskSecretDefaults: boolean): string[] {
  const hideDefault = field.secret && maskSecretDefaults;
  const meta: string[] = [];
  meta.push(field.type);
  meta.push(field.required ? "required" : "optional");
  if (field.enumValues) meta.push(`enum: ${field.enumValues.join("|")}`);
  if (field.defaultValue !== undefined && !hideDefault) {
    meta.push(`default: ${formatDefault(field.defaultValue)}`);
  }
  if (field.secret) meta.push("secret");

  const out: string[] = [];
  out.push(`# ${field.key} (${meta.join(", ")})`);
  if (field.description) {
    for (const descLine of field.description.split(/\r?\n/)) {
      out.push(`# ${descLine}`);
    }
  }

  let value = "";
  if (field.defaultValue !== undefined) {
    if (field.secret && maskSecretDefaults) {
      value = "";
    } else {
      value = formatValue(field.defaultValue);
    }
  }
  out.push(`${field.key}=${value}`);
  return out;
}

function formatDefault(value: unknown): string {
  if (typeof value === "string") return JSON.stringify(value);
  return String(value);
}

function formatValue(value: unknown): string {
  if (typeof value === "string") {
    return /[\s"'#]/.test(value) ? JSON.stringify(value) : value;
  }
  return String(value);
}
