import type { EnvField } from "../introspect.js";

export interface MarkdownDocsOptions {
  /** H1/H2-style title rendered above the table. Default: `"Environment Variables"`. */
  title?: string;
  /** Optional paragraph rendered between the title and the table. */
  intro?: string;
  /** End-of-line. Default: `"\n"`. */
  eol?: string;
}

/**
 * Generate a Markdown document describing the environment variables a
 * service expects. Designed to be committed as `ENV.md` and read by
 * infra / SRE teams without forcing them into the TypeScript source.
 */
export function generateMarkdownDocs(
  fields: readonly EnvField[],
  options: MarkdownDocsOptions = {},
): string {
  const eol = options.eol ?? "\n";
  const title = options.title ?? "Environment Variables";

  const lines: string[] = [];
  lines.push(`# ${title}`, "");
  if (options.intro) lines.push(options.intro, "");

  lines.push(
    "| Key | Type | Required | Default | Secret | Description |",
    "| --- | ---- | -------- | ------- | ------ | ----------- |",
  );

  for (const field of fields) {
    lines.push(renderRow(field));
  }

  lines.push("");
  lines.push(
    `_Generated by [@changsik00/node-settings](https://github.com/Changsik00/node-settings)._`,
  );
  return lines.join(eol) + eol;
}

function renderRow(field: EnvField): string {
  const typeCell =
    field.type === "enum" && field.enumValues
      ? `enum (\`${field.enumValues.join("` \\| `")}\`)`
      : `\`${field.type}\``;
  const requiredCell = field.required ? "yes" : "no";
  const defaultCell =
    field.defaultValue === undefined
      ? "—"
      : `\`${formatDefault(field.defaultValue)}\``;
  const secretCell = field.secret ? "yes" : "—";
  const descriptionCell = (field.description ?? "").replace(/\|/g, "\\|");
  return `| \`${field.key}\` | ${typeCell} | ${requiredCell} | ${defaultCell} | ${secretCell} | ${descriptionCell} |`;
}

function formatDefault(value: unknown): string {
  if (typeof value === "string") return value;
  return String(value);
}
