import type { EnvField } from "../introspect.js";

export interface TfvarsOptions {
  /** Header banner placed at the top of the file. */
  header?: string;
  /** Group secret variables under a separate `# Secrets` section. Default: true. */
  groupSecrets?: boolean;
  /**
   * Pre-fill specific variables with concrete values. Useful for
   * pipelines that need a non-placeholder file at write time. Secrets
   * are still rendered with a REPLACE_ME placeholder unless explicitly
   * listed here.
   */
  values?: Record<string, string | number | boolean>;
  /** End-of-line. Default: `"\n"`. */
  eol?: string;
}

/**
 * Generate the contents of a Terraform `.tfvars` file from
 * introspected env-field metadata. The output uses HCL2 syntax:
 *
 * ```hcl
 * # Description of the variable
 * VARIABLE_NAME = "REPLACE_ME"
 * ```
 *
 * Required values default to `"REPLACE_ME"`; optional fields use
 * their schema default. Booleans and numbers are emitted as their
 * native HCL types; everything else is quoted as a string. Override
 * any key via `options.values`.
 *
 * Pair with a `variable "VARIABLE_NAME" {}` block in your Terraform
 * module — this generator only produces the values file, not the
 * variable declarations (those live alongside the resources that
 * read them, so they're project-specific).
 */
export function generateTfvars(
  fields: readonly EnvField[],
  options: TfvarsOptions = {},
): string {
  const eol = options.eol ?? "\n";
  const groupSecrets = options.groupSecrets ?? true;
  const values = options.values ?? {};

  const header =
    options.header ??
    [
      "# Generated by @env-kit/node-settings.",
      "# Re-run `node-settings generate tfvars` to refresh.",
      "# Required values are 'REPLACE_ME' — fill them in (or pass via TF_VAR_*).",
      "# DO NOT commit real secret values; pull them from a secret store.",
    ].join(eol);

  const lines: string[] = [header, ""];

  type Entry = EnvField | { divider: string };
  const ordered: Entry[] = groupSecrets
    ? [
        ...fields.filter((f) => !f.secret),
        ...(fields.some((f) => f.secret)
          ? [{ divider: "# --- Secrets ---" }]
          : []),
        ...fields.filter((f) => f.secret),
      ]
    : [...fields];

  for (const entry of ordered) {
    if ("divider" in entry) {
      lines.push("", entry.divider, "");
      continue;
    }
    lines.push(...renderField(entry, values));
    lines.push("");
  }

  while (lines.at(-1) === "") lines.pop();
  lines.push("");
  return lines.join(eol);
}

function renderField(
  field: EnvField,
  values: Record<string, string | number | boolean>,
): string[] {
  const out: string[] = [];
  const tags: string[] = [field.type];
  tags.push(field.required ? "required" : "optional");
  if (field.enumValues) tags.push(`enum: ${field.enumValues.join("|")}`);
  if (field.secret) tags.push("secret");
  out.push(`# ${field.key} (${tags.join(", ")})`);
  if (field.description) {
    for (const line of field.description.split(/\r?\n/)) {
      out.push(`# ${line}`);
    }
  }

  const override = values[field.key];
  let literal: string;
  if (override !== undefined) {
    literal = formatHcl(override);
  } else if (field.required || field.secret) {
    literal = `"REPLACE_ME"`;
  } else if (field.defaultValue !== undefined) {
    literal = formatHcl(field.defaultValue as string | number | boolean);
  } else {
    literal = `""`;
  }
  out.push(`${field.key} = ${literal}`);
  return out;
}

function formatHcl(value: string | number | boolean): string {
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "number") return String(value);
  return JSON.stringify(String(value)); // double-quoted, escaped
}
