#!/usr/bin/env node
/**
 * Verify that select ` ```ts ` / ` ```typescript ` code blocks in the
 * project's docs actually type-check.
 *
 * Design: **opt-in**. Only blocks preceded by `<!-- doc-test:check -->`
 * are checked. Most docs contain pedagogical fragments (partial object
 * literals, `// ...`, wrong-pattern illustrations) that are not meant
 * to compile in isolation. Marking the ones users are most likely to
 * copy-paste catches drift on the *load-bearing* examples without
 * fighting every comment-laced snippet.
 *
 * Imports inside blocks that reference `"@env-kit/node-settings"`
 * (or its `./generators` subpath) are rewritten to relative imports
 * into `../src/` so the block compiles inside this repo.
 *
 * Run after `pnpm build` (the package name resolution above relies
 * on `dist/` only insofar as the .ts source still lives in `src/`).
 *
 * Each checked block:
 *   - is written to `.doc-check-tmp/block-N.ts` at top level
 *   - inherits a minimal tsconfig with module resolution pointed at
 *     the project's `node_modules`
 *   - is compiled with `tsc --noEmit`
 */
import { execSync } from "node:child_process";
import {
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, resolve as resolvePath } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolvePath(HERE, "..");
const TMP_DIR = resolvePath(ROOT, ".doc-check-tmp");

const SOURCES = [
  "README.md",
  "AGENTS.md",
  "RELEASING.md",
  "sample/README.md",
  ...readdirIfExists("docs")
    .map((f) => `docs/${f}`)
    .filter((p) => p.endsWith(".md")),
];

function readdirIfExists(dir) {
  try {
    statSync(resolvePath(ROOT, dir));
    return readdirSync(resolvePath(ROOT, dir));
  } catch {
    return [];
  }
}

const FENCE = /^```(ts|typescript)\b/;
const CHECK_MARKER = /<!--\s*doc-test:check\s*-->/;

function extractBlocks(file) {
  const absPath = resolvePath(ROOT, file);
  let content;
  try {
    content = readFileSync(absPath, "utf8");
  } catch {
    return [];
  }
  const lines = content.split("\n");
  const blocks = [];
  let idx = 0;
  let i = 0;
  while (i < lines.length) {
    if (!FENCE.test(lines[i])) {
      i += 1;
      continue;
    }
    // Find the nearest previous non-empty line; check for the marker.
    let prev = "";
    for (let p = i - 1; p >= 0; p -= 1) {
      if (lines[p].trim()) {
        prev = lines[p];
        break;
      }
    }
    if (!CHECK_MARKER.test(prev)) {
      // Default-skipped. Advance past the closing fence.
      let j = i + 1;
      while (j < lines.length && !/^```/.test(lines[j])) j += 1;
      i = j + 1;
      continue;
    }
    const startLine = i + 2; // first code line is fence + 1, 1-based
    const codeLines = [];
    let j = i + 1;
    while (j < lines.length && !/^```/.test(lines[j])) {
      codeLines.push(lines[j]);
      j += 1;
    }
    blocks.push({
      file,
      startLine,
      code: codeLines.join("\n"),
      idx: idx++,
    });
    i = j + 1;
  }
  return blocks;
}

function rewriteImports(code) {
  // Rewrite the public package name to the in-repo source path so the
  // block compiles inside this monorepo. We use the `.ts` source rather
  // than `dist/.js` so the script doesn't require a prior `pnpm build`.
  return code
    .replace(
      /(["'])@env-kit\/node-settings\/generators\1/g,
      `"${resolvePath(ROOT, "src/generators/index.ts").replace(/\\/g, "/")}"`,
    )
    .replace(
      /(["'])@env-kit\/node-settings\1/g,
      `"${resolvePath(ROOT, "src/index.ts").replace(/\\/g, "/")}"`,
    );
}

const allBlocks = SOURCES.flatMap(extractBlocks);

if (allBlocks.length === 0) {
  console.log(
    "OK    (no doc-test:check blocks found — add `<!-- doc-test:check -->` above a ```ts fence to opt in)",
  );
  process.exit(0);
}

rmSync(TMP_DIR, { recursive: true, force: true });
mkdirSync(TMP_DIR, { recursive: true });

const fileMap = new Map();
for (const block of allBlocks) {
  const safeName = `${block.file.replace(/[^a-zA-Z0-9]/g, "_")}-block-${block.idx}.ts`;
  const tmpPath = resolvePath(TMP_DIR, safeName);
  const header = `// generated by verify-docs.mjs — block from ${block.file}:${block.startLine}\n`;
  writeFileSync(tmpPath, header + rewriteImports(block.code));
  fileMap.set(tmpPath, block);
}

const tsconfigPath = resolvePath(TMP_DIR, "tsconfig.json");
writeFileSync(
  tsconfigPath,
  JSON.stringify(
    {
      compilerOptions: {
        target: "ES2022",
        module: "NodeNext",
        moduleResolution: "NodeNext",
        lib: ["ES2022"],
        strict: true,
        noImplicitAny: false,
        skipLibCheck: true,
        esModuleInterop: true,
        allowSyntheticDefaultImports: true,
        resolveJsonModule: true,
        // The import rewriter produces .ts paths into ../src; enable
        // ts-extensions so module resolution accepts them.
        allowImportingTsExtensions: true,
        noEmit: true,
      },
      include: ["./*.ts"],
    },
    null,
    2,
  ),
);

let stdout = "";
let stderr = "";
let exitCode = 0;
try {
  stdout = execSync(`npx --offline tsc -p ${tsconfigPath} --pretty false`, {
    cwd: ROOT,
    encoding: "utf8",
  });
} catch (err) {
  exitCode = err.status ?? 1;
  stdout = err.stdout?.toString() ?? "";
  stderr = err.stderr?.toString() ?? "";
}

if (exitCode === 0) {
  rmSync(TMP_DIR, { recursive: true, force: true });
  console.log(
    `OK    ${allBlocks.length} doc code block${allBlocks.length === 1 ? "" : "s"} (marked doc-test:check) compile cleanly`,
  );
  process.exit(0);
}

// Remap tsc errors back to source file + line.
const out = (stdout + stderr).split("\n");
// File path pattern in tsc output is project-relative or absolute.
const errorRegex = /^(.+?\.ts)\((\d+),(\d+)\):\s+(.+)$/;
const remapped = [];
for (const line of out) {
  const m = errorRegex.exec(line);
  if (!m) {
    if (line.trim()) remapped.push(line);
    continue;
  }
  const tmpPath = resolvePath(ROOT, m[1]);
  const block = fileMap.get(tmpPath);
  if (!block) {
    remapped.push(line);
    continue;
  }
  const tmpLine = parseInt(m[2], 10);
  // 1 header line is prepended; block code starts on line 2 of the temp file.
  const sourceLine = block.startLine + Math.max(0, tmpLine - 2);
  remapped.push(`  ${block.file}:${sourceLine}: ${m[4]}`);
}

console.error("FAIL  doc code blocks marked doc-test:check have type errors:");
console.error("");
for (const line of remapped) console.error(line);
console.error("");
console.error(
  "Fix the snippets, or remove the `<!-- doc-test:check -->` marker above the fence.",
);
console.error(`(temp files left in ${TMP_DIR} for inspection)`);
process.exit(1);
